services:
  edgex-editor:
    image: rajasekhar0790/edgex-editor:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Set your backend API URL at build time (Vite env)
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://localhost:8080}
    container_name: edgex-editor
    ports:
      - "8088:80"
    restart: unless-stopped
